  # Site Settings
title: Friends of Sullivan
email: harry@friendsofsullivan.com
description: >
  We are a community of past alumni, friends, family, local parents and more, working together to sustain a future for Sullivan equivalent to the 140 years that have come before us.
baseurl: "/fos"
url: "http://localhost:4000"
twitter_username: sullivanalumni
github_username:  friendsofsullivan
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM